// website/components/me/CardContacts.tsx
import React from 'react';
import { Icon } from '@/components/common/Icon';

export function CardContacts() {
  return (
    <div className="join join-vertical mx-auto">
      <a
        id="gh"
        href="https://github.com/skornel02"
        target="_blank"
        rel="noreferrer noopener"
        className="btn join-item flex items-center gap-2"
      >
        <Icon height={32} width={32} name="mdi:github" color="#333333" />
        <span> Github</span>
      </a>
      <a
        id="fb"
        href="https://www.facebook.com/stefankornel02"
        target="_blank"
        rel="noreferrer noopener"
        className="btn join-item flex items-center gap-2"
      >
        <Icon height={32} width={32} name="mdi:facebook-box" color="#4267B2" />
        <span> Facebook</span>
      </a>
      <a
        id="linkedin"
        href="https://linkedin.com/in/skornel02"
        target="_blank"
        rel="noreferrer noopener"
        className="btn join-item flex items-center gap-2"
      >
        <Icon height={32} width={32} name="mdi:linkedin" color="#0077B5" />
        <span> LinkedIn</span>
      </a>
      <a
        id="mail"
        href="https://aemail.com/Elgl"
        className="btn join-item flex items-center gap-2"
      >
        <Icon height={32} width={32} name="mdi:email-fast" color="#c71610" />
        <span> Email</span>
      </a>
    </div>
  );
}

export default CardContacts;

// src/lib/me/CardContacts.svelte
<script lang="ts">
	import FaGithub from 'svelte-icons/fa/FaGithub.svelte';
	import FaFacebook from 'svelte-icons/fa/FaFacebook.svelte';
	import FaEnvelope from 'svelte-icons/fa/FaEnvelope.svelte';
</script>

<div class="column">
	<div class="row">
		<div class="col-12 col-sm-8 offset-0 offset-sm-2 py-1">
			<a id="gh" href="https://github.com/skornel02" target="_blank" rel="noreferrer noopener" class="btn btn-secondary">
				<i class="icon"> <FaGithub /></i>
				Github
			</a>
		</div>
	</div>
	<div class="row">
		<div class="col-12 col-sm-8 offset-0 offset-sm-2 py-1">
			<a
				id="fb"
				href="https://www.facebook.com/stefankornel02"
				target="_blank"
				rel="noreferrer noopener"
				class="btn btn-secondary"
			>
				<i class="icon"> <FaFacebook /></i>
				Facebook
			</a>
		</div>
	</div>
	<div class="row d-none">
		<div class="col-12 col-sm-8 offset-0 offset-sm-2 py-1">
			<a id="mail" href="mailto:contact@skornel02.hu" class="btn btn-secondary">
				<i class="icon"> <FaEnvelope /></i>
				Email
			</a>
		</div>
	</div>
</div>

<style lang="scss">
	.btn {
		display: flex;
		justify-content: center;
		align-items: center;
		width: 100%;
		font-weight: bold;
	}
	.icon {
		display: inline;
		width: 32px;
		height: 32px;
		margin: 0 6px;
	}
	#gh {
		color: #171515;
		background-color: white !important;
	}
	#fb {
		color: white;
		background-color: #4267b2 !important;
	}
	#mail {
		color: black;
		background-color: white !important;
		i {
			color: #ea4335;
		}
	}
</style>
