// website/src/components/search/FuseAutocomplete.svelte
<script lang="ts" generics="T">
	import Fuse from 'fuse.js';

	export let fuse: Fuse<T>;
	export let handleSearchResults: undefined | ((results: Fuse.FuseResult<T>[]) => void) = undefined;
	export let dialogNamePicker: undefined | ((result: Fuse.FuseResult<T>) => string) = undefined;
	export let dialogLinkPicker: (result: Fuse.FuseResult<T>) => string | undefined = () => undefined;

	const searchEnabled = dialogNamePicker !== undefined;

	let searchBoxContent: string = '';
	let searchResults: Fuse.FuseResult<T>[] = [];

	const handleSearch = () => {
		const result = fuse.search(searchBoxContent);

		if (searchEnabled) {
			searchResults = result;
		}

		if (handleSearchResults) {
			handleSearchResults(result);
		}
	};
</script>

<div class="dropdown w-full" class:dropdown-open={searchResults.length !== 0}>
	<div class="form-control">
		<label class="label" for="postsSearchBox">
			<span class="label-text">Find what you are looking for!</span>
		</label>
		<input
			id="postsSearchBox"
			type="text"
			placeholder="Search..."
			class="input input-bordered"
			bind:value={searchBoxContent}
			on:input={handleSearch} />
	</div>
	{#if searchEnabled}
		<ul class="dropdown-content menu bg-primary">
			{#if searchResults.length === 0}
				<li class="text-white">No results found</li>
			{/if}

			{#each searchResults as result}
				<li
					class:disabled={dialogLinkPicker && dialogLinkPicker(result) === undefined}
					class="text-white">
					<a href={dialogLinkPicker && dialogLinkPicker(result)}>
						{dialogNamePicker && dialogNamePicker(result)} ({((result.score ?? 0) * 100).toFixed(
							0
						)}%)
					</a>
				</li>
			{/each}
		</ul>
	{/if}
</div>

// website/components/search/FuseAutocomplete.tsx
'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import Fuse, { type FuseResult } from 'fuse.js';

interface FuseAutocompleteProps<T> {
  fuse: Fuse<T>;
  dialogNamePicker?: (result: FuseResult<T>) => string;
  dialogLinkPicker?: (result: FuseResult<T>) => string | undefined;
}

export function FuseAutocomplete<T>({
  fuse,
  dialogNamePicker,
  dialogLinkPicker,
}: FuseAutocompleteProps<T>) {
  const [searchQuery, setSearchQuery] = useState('');
  const [results, setResults] = useState<FuseResult<T>[]>([]);

  const handleSearch = (e: React.ChangeEvent<HTMLInputElement>) => {
    const query = e.target.value;
    setSearchQuery(query);
    if (query.trim().length > 0) {
      setResults(fuse.search(query));
    } else {
      setResults([]);
    }
  };

  return (
    <div className={`dropdown w-full ${results.length > 0 ? 'dropdown-open' : ''}`}>
      <div className="form-control w-full">
        <label className="label" htmlFor="postsSearchBox">
          <span className="label-text">Find what you are looking for!</span>
        </label>
        <input
          id="postsSearchBox"
          type="text"
          placeholder="Search..."
          className="input input-bordered w-full"
          value={searchQuery}
          onChange={handleSearch}
        />
      </div>

      {searchQuery.trim().length > 0 && (
        <ul className="dropdown-content menu bg-primary text-white rounded-box z-50 w-full p-2 shadow-xl mt-1">
          {results.length === 0 ? (
            <li className="p-2 text-white/80">No results found</li>
          ) : (
            results.map((result, idx) => {
              const name = dialogNamePicker ? dialogNamePicker(result) : '';
              const href = dialogLinkPicker ? dialogLinkPicker(result) : undefined;
              const matchScore = ((1 - (result.score ?? 0)) * 100).toFixed(0);

              return (
                <li key={idx}>
                  {href ? (
                    <Link
                      href={href}
                      className="hover:bg-primary-focus text-white flex justify-between"
                      onClick={() => {
                        setSearchQuery('');
                        setResults([]);
                      }}
                    >
                      <span>{name}</span>
                      <span className="text-xs opacity-75">{matchScore}%</span>
                    </Link>
                  ) : (
                    <span>{name}</span>
                  )}
                </li>
              );
            })
          )}
        </ul>
      )}
    </div>
  );
}

export default FuseAutocomplete;
