// src/lib/card/CardNavigation.svelte
<script lang="ts">
	import {Home, QrCode, List} from 'lucide-svelte';

	export let home = true;
	export let details = true;
	export let card = true;
</script>

<div class="flex justify-center">
	<div class="btn-group">
		{#if card}
			<a id="home" href="/card" class="btn btn-outline btn-secondary hover:bg-primary">
				<QrCode size="{32}" />
			</a>
		{:else if details}
			<a id="details" href="/me" class="btn btn-outline btn-secondary hover:bg-primary">
				<List size="{32}" />
			</a>
		{/if}
		{#if home}
			<a id="home" href="/" class="btn btn-outline btn-secondary hover:bg-primary" data-sveltekit-reload>
				<Home size="{32}" />
			</a>
		{/if}
	</div>
</div>

// website/components/me/CardNavigation.tsx
import React from 'react';
import Link from 'next/link';
import { Icon } from '@/components/common/Icon';

interface CardNavigationProps {
  home?: boolean;
  details?: boolean;
  card?: boolean;
}

export function CardNavigation({
  home = false,
  details = false,
  card = false,
}: CardNavigationProps) {
  return (
    <div className="flex justify-center">
      <div className="join">
        {card && (
          <Link
            id="business-card-link"
            href="/business-card"
            className="btn btn-outline btn-secondary hover:bg-primary join-item"
            title="Business Card"
          >
            <Icon name="mdi:qrcode" height={32} width={32} />
          </Link>
        )}
        {details && (
          <Link
            id="details-link"
            href="/me"
            className="btn btn-outline btn-secondary hover:bg-primary join-item"
            title="Details"
          >
            <Icon name="mdi:account-details" height={32} width={32} />
          </Link>
        )}
        {home && (
          <Link
            id="home-link"
            href="/"
            className="btn btn-outline btn-primary hover:bg-primary join-item"
            title="Home"
          >
            <Icon name="mdi:home" height={32} width={32} />
          </Link>
        )}
      </div>
    </div>
  );
}

export default CardNavigation;
