// website/src/components/me/MeCard.svelte
<script lang="ts">
	import CardTitle from './CardTitle.svelte';
	import {fade, type FadeParams} from 'svelte/transition';

	const fadeParams: FadeParams = {
		duration: 750,
		delay: 200,
	};

	let loaded = false;

	const onLoad = () => {
		loaded = true;
	};
</script>

<svelte:head>
	<title>Stefán Kornél</title>
	<meta name="description" content="Digital personal information card" />
</svelte:head>

<div class="card w-80 sm:w-96 bg-base-100 m-auto z-10" in:fade={{delay: 200}} out:fade={{duration: 150}}>
	<div class="card-body" class:card-loaded={loaded}>
		<div id="nameSlot" class="sm:card-title justify-center">
			<CardTitle on:load={onLoad} />
		</div>
		{#if loaded}
			<hr in:fade={fadeParams} />
			<div id="faceSlot" class="mx-auto avatar ring ring-primary rounded" in:fade={fadeParams}>
				<!-- <Face class="rounded ring-offset-base-100 ring-offset-2" /> -->
				<slot name="face" />
			</div>
			<hr in:fade={fadeParams} />
			<div class="flex justify-center items-center" in:fade={fadeParams}>
				<slot name="contacts" />
				<!-- <CardContacts /> -->
			</div>
			<hr in:fade={fadeParams} />
			<div id="navigationSlot" in:fade={fadeParams}>
				<slot name="navigation" />
			</div>
		{/if}
	</div>
</div>

<style>
	.card-body {
		border-color: var(--color-secondary);
		height: fit-content;
		max-height: 100px;
		transition: max-height 0.5s;
	}
	.card-loaded {
		max-height: 800px;
	}
	#nameSlot {
		height: 3rem;
	}
	hr {
		color: #f00;
		border: 0;
		height: 1px;
	}
</style>

// website/components/me/MeCard.tsx
'use client';

import React, { useState } from 'react';
import { CardTitle } from './CardTitle';
import { CardContacts } from './CardContacts';
import { CardNavigation } from './CardNavigation';

export function MeCard() {
  const [loaded, setLoaded] = useState(false);

  return (
    <div className="card w-80 sm:w-96 bg-base-100 m-auto z-10 shadow-xl border border-secondary transition-all duration-300">
      <div
        className={`card-body transition-all duration-700 overflow-hidden ${
          loaded ? 'max-h-[850px]' : 'max-h-28'
        }`}
      >
        <div id="nameSlot" className="sm:card-title justify-center h-12 flex items-center">
          <CardTitle onDone={() => setLoaded(true)} />
        </div>

        <div
          className={`transition-opacity duration-700 ease-in-out ${
            loaded ? 'opacity-100' : 'opacity-0 pointer-events-none'
          }`}
        >
          <div className="divider my-1"></div>

          <div
            id="faceSlot"
            className="mx-auto avatar ring ring-primary rounded-lg overflow-hidden w-40 h-40 my-2"
          >
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src="/images/people/sk.jpeg"
              alt="Kornél portrait"
              className="w-full h-full object-cover"
            />
          </div>

          <div className="divider my-1"></div>

          <div className="flex justify-center items-center my-2">
            <CardContacts />
          </div>

          <div className="divider my-1"></div>

          <div id="navigationSlot" className="mt-2">
            <CardNavigation home={true} card={true} />
          </div>
        </div>
      </div>
    </div>
  );
}

export default MeCard;
